### ISSUE TITLE
Manage per-device state for validation

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#1008]
When gNMI set requests are received on the northbound, part of the handling of the requests involves validating them against the current state of the devices. But the way this validation is done currently is an inefficient relic of the days when stores were local. Device changes are replayed and aggregated, and changes are validated against the aggregated state. Config nodes should instead maintain the aggregated state of each device so that reads can be serviced and writes can be validated without computation overhead during the requests. This would significantly improve performance.

**Comment by SeanCondon** [comment]
@kuujo I think this is also solved now with the DeviceStateStore? Please confirm
