### ISSUE TITLE
Implement caching for stores

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#1009]
Stores for onos-config were written without caches to ensure the backend was getting used while development was ongoing. But caching remains important to improving the performance of stores used by controllers/reconcilers. The change stores at least should be cached to provide fast reads for control loops.

**Comment by SeanCondon** [comment]
@kuujo  I think this is solved now? Please confirm.

**Comment by adibrastegarnia** [comment]
@SeanCondon 
I will take this out of Q3. According to the discussion with @kuujo controllers can read a lot from the stores, so caching of the IndexedMap can help a lot but it should be done when we have onos-config stable.
