### ISSUE TITLE
Upgrade to Go v13.0 - currently using 1.12 in go.mod

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#1051]
**Is your feature request related to a problem? Please describe.**
Currently all our Go code is build against Go 1.12. 

**Describe the solution you'd like**
Use go compiler 1.13 and update any dependenices

**Describe alternatives you've considered**
Leaving it on 1.12 is possible, but this is only supported until 1.14 comes out (looks like there's a 6 month cadence to releases, so i might be due March '20)

**Additional context**
On the TST meeting on 22/1/2020 it was agreed that this should go ahead. If it does not cause too much disruption it can happen before the 1.0 release (expected Feb '20)

**Comment by adibrastegarnia** [comment]
@SeanCondon 
I had a quick test on my local machine. Except some of the deps gets updated (specially gogo protobuf library) everything else looks fine but other developers should try it as well.

**Comment by SeanCondon** [comment]
on 1.14 already
