### ISSUE TITLE
gNMI client Subscribe() operation blocks the calling thread

### ISSUE THREAD

**Issue by ray-milkey** [onosproject/onos-config#1064]
If you use the Subscribe() function on a gNMI client to request a subscription from an onos-config instance the request will block. You have to wrap it in a goroutine to be able to get back any events.

**Comment by Andrea-Campanella** [comment]
I'm not sure this is an issue. I think that is the point of a subscribe, you want to continue be listening for events. at least that is how it's implemented in the gNMI subscriptions I've seen. how would you do it ?

**Comment by kuujo** [comment]
Is there a code example of what a working subscribe looks like? I can't find much from the docs.

**Comment by Andrea-Campanella** [comment]
@kuujo  https://docs.onosproject.org/onos-config/docs/gnmi/ section `Northbound Subscribe Request for Stream Notifications via gNMI`

**Comment by ray-milkey** [comment]
@Andrea-Campanella the Subscribe() call blocks. There is no way to listen to events without another thread. This would make this API very hard to use for languages that don't supply threading, like Python.
