### ISSUE TITLE
Publish documentation as gitbook

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#107]

**Comment by Andrea-Campanella** [comment]
I did some investigation of this.
Pricing is free for open source projects but we might also reuse the opencord account. 
It seems that the integration is pretty straight forward https://docs.gitbook.com/integrations/github.
The way `CORD` does it is to have a separate `docs` repo (https://github.com/opencord/docs) that gets then published to https://guide.opencord.org.
We would need to decide either to publish X elements (onos-config/onos-control/onos-ran/onos-topo/simulators) or move the docs under one repo and consolidate everything there.

**Comment by SeanCondon** [comment]
I think this is handled now by MkDocs in the onos-docs repo and available at https://docs.onosproject.org Andrea - can you close if this is OK
