### ISSUE TITLE
`sync.subscribeOpState()`  gives error if there are no subscribe paths  

### ISSUE THREAD

**Issue by k1eran** [onosproject/onos-config#1100]
**Describe the bug**
`sync.subscribeOpState(target, errChan)`  should handle when there are no subscribe paths 

**To Reproduce**
1.Discover a device with a model with no read-only paths i.e. just  CONFIG and no OPERATIONAL or STATE items 

2.  onos-config logs will show a error like ...

```

{"level":"INFO","ts":"2020-03-10T17:16:10.525Z","southbound/synchronizer":"southbound/synchronizer","caller":"synchronizer/synchronizer.go:460","msg":"Getting OPERATIONAL partition for nc1633"}
{"level":"INFO","ts":"2020-03-10T17:16:10.957Z","southbound/synchronizer":"southbound/synchronizer","caller":"synchronizer/synchronizer.go:363","msg":"Handling 2 received OpState paths. nc1633"}
{"level":"INFO","ts":"2020-03-10T17:16:10.958Z","southbound/synchronizer":"southbound/synchronizer","caller":"synchronizer/synchronizer.go:433","msg":"Subscribing to 0 paths. nc1633"}
{"level":"WARN","ts":"2020-03-10T17:16:10.958Z","southbound/synchronizer":"southbound/synchronizer","caller":"synchronizer/synchronizer.go:443","msg":"Error in subscribecould not create a gNMI for subscription: Query.Queries not set"}
{"level":"INFO","ts":"2020-03-10T17:16:10.958Z","southbound/synchronizer":"southbound/synchronizer","caller":"synchronizer/factory.go:129","msg":"Received event nc1633 EventTypeErrorDeviceConnect 2020-03-10T17:16:10Z {{ <nil> }}"}
{"level":"INFO","ts":"2020-03-10T17:16:10.958Z","southbound/synchronizer":"southbound/synchronizer","caller":"synchronizer/factory.go:129","msg":"Received event nc1633 EventTypeErrorSubscribe, EventTypeErrorMissingModelPlugin, EventTypeErrorTranslation 2020-03-10T17:16:10Z {{ %!s(*errors.errorString=&{could not create a gNMI for subscription: Query.Queries not set}) }}"}
{"level":"INFO","ts":"2020-03-10T17:16:10.958Z","manager":"manager","caller":"manager/devicehandler.go:35","msg":"Device nc1633 disconnected or had error in connection %!s(<nil>)"}
{"level":"INFO","ts":"2020-03-10T17:16:10.958Z","southbound/synchronizer":"southbound/synchronizer","caller":"synchronizer/factory.go:208","msg":"Connecting to device id:\"nc1633\" 
```

**Expected behavior**
onos-config should not try to subscribe when there are no read-only paths (or if it does subscribe ensure no errors)

There should not be a EventTypeErrorSubscribe and onos-config  should not get into a cycle of retries.

**Logs, text or screenshots**
See above.

**Additional context**
One  solution that works (but I'm not sure if it's the best)  is to exit early from `subscribeOpState` function e.g.

```
func (sync *Synchronizer) subscribeOpState(target southbound.TargetIf, errChan chan<- events.DeviceResponse) {

// SNIP 

if (len(subscribePaths)) == 0 {
	log.Warnf("No paths for %s so don't try to subscribe", string(sync.key))
	return
}

// SNIP
```
}

**Comment by SeanCondon** [comment]
The model plugin should implement the function `GetStateMode()` to return `0`. 
See https://github.com/onosproject/config-models/blob/6992f473b24033d3f0a00165a472992e4bda133d/modelplugin/testdevice-1.0.0/modelmain.go#L73 for an example.

This acts as a way to tell the synchronizer NOT to retrieve state from that device type.

I will be closing this issue once you have verified this.

**Comment by k1eran** [comment]
@SeanCondon I've verified that approach now  and it works for me now, thanks for clarification.

**Comment by k1eran** [comment]
Perhaps its worthwhile an  extra  comment in `pkg/modelregistry/modelregistry.go` in the `GetStateOpState` description to emphasise if that if used  there **must** be 1 or more item? Also perhaps ` subscribeOpState`  should generate a more descriptive error specifying something wrong regarding an inconsistent model.
These just suggestions and pretty minor.

**Comment by SeanCondon** [comment]
will do
