### ISSUE TITLE
onos-config needs a way to recognize "non-config" device in "onos-topo"

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#1113]
**Is your feature request related to a problem? Please describe.**
Not all devices listed in `onos-topo` support gNMI, and so `onos-config` should not keep trying to reconnect to them.

For instance the `ran-simulator` puts all of the Cell towers in to `onos-topo` so that `onos-ric` can be aware of them.These devices present an endpoint like "ran-simulator:51xx". With 100 towers in a typical configuration, `onos-config` will needlessly expend many cycles trying to reconnect to these devices.

**Describe the solution you'd like**
There are a few different ways to solve this (please add any advantages and disadvantages below):

1. an opt out solution - there could be an attribute added to Device in `onos-topo` to say the device does not have gNMI e.g. `gnmi:no`
1. an opt in solution - alternatively there could be an attribute added to Device in `onos-topo` to say the device does have gNMI e.g. `gnmi:yes`
1. an automatic solution - there could be some mechanism that can tell from the connection that it's not a gNMI capable device e.g. if the response to getCapabilities is an error, and it should not try again
1. some combination of the above

**Describe alternatives you've considered**
an alternative is not to start the `onos-control` microservice while ran-simulator service is running. This means reduced functionality and is only a stop gap measure. 

**Additional context**

**Comment by Andrea-Campanella** [comment]
I think it's possibile doing a filtering just on the protocols present in the device list 
https://github.com/onosproject/onos-topo/blob/master/api/device/device.proto#L26
