### ISSUE TITLE
RBAC: create a grpc interceptor to strip OpenID JWT info from gRPC request

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#1151]
This is for onos-config RBAC
https://jira.opennetworking.org/browse/AETHER-315

create a grpc interceptor to strip OpenID JWT info from gRPC request
The general idea can be seen here
https://talks.godoc.org/github.com/lpabon/go-slides/2019/kubecon-na-2019.slide#16

If possible this can be pushed out to onos-lib-go to be used with other modules, but initially it's fine to have it only on onos-config

**Comment by adibrastegarnia** [comment]
@SeanCondon 
Should we close this?
