### ISSUE TITLE
Move device.proto from onos-topo to onos-config

### ISSUE THREAD

**Issue by shadansari** [onosproject/onos-config#1163]
- onos-topo/api/device/device.proto is only used by onos-config and is better moved from onos-topo to onos-config
- Add checks and validation to ObjectToDevice() and DeviceToObject()

**Comment by adibrastegarnia** [comment]
@shadansari 
Perhaps I am missing something or that is just an intermediate step for a complete migration. if that is related to topo api somehow that should be kept in onos-topo or we should find a way to do the migration properly. My understanding is  the new topo API should provide whatever is needed by onos-config without moving the device API to onos-config.       

Just my two cents

**Comment by SeanCondon** [comment]
It would be worth investigating if `Device` can be removed from `onos-config` altogether.

**Comment by shadansari** [comment]
@adibrastegarnia @SeanCondon - since onos-config concerns itself with "devices" - physical (e.g. gNB) or virtual (e.g. RIC), I presumed that it would need some data structure to represent it and we could use the existing device.proto for that purpose. I am not too certain of the benefits of using Object or Entity.
