### ISSUE TITLE
Enhance net-changes and changes diags commands

### ISSUE THREAD

**Issue by tomikazi** [onosproject/onos-config#118]
Add next level of information describing the submitted change(s)

**Comment by SeanCondon** [comment]
I have enhanced in the following ways:

- net-changes now shows the full hierarchy of device and change
- changes has been enhanced to show all, 1 or several change IDs and show the paths
- configs has been created to allow showing all, 1 or several configs and show the associated changes
- rollback has been added to rollback a named or the last change (if no name given)

So I'm closing this comment - please open a new one for further functions
