### ISSUE TITLE
Topology Destroy Issue

### ISSUE THREAD

**Issue by AneeqAbid06** [onosproject/onos-config#1253]
Hi,

I ran the following command to create a test MININET Optical topology using a remote ONOS and now it won't let me destroy the topology.

sudo -E python onos/tools/test/topos/opticalTestBig.py

Running the command "wipe-out please" in ONOS deletes the topology but it immediately reappears. Please guide how I can clean the configuration.

**Comment by SeanCondon** [comment]
This repo is for `onos-config` in the new µONOS architecture. For issues relating to Classic ONOS, you should post them on the `onos-dev` google group, or in Slack "ONF-Community" on the `onos-dev` channel

I think you will have to stop mininet, and then do `wipe-out please` to reset everything
