### ISSUE TITLE
onos-config pod stuck in Init:CrashLoopBackOff with  KubeOVN

### ISSUE THREAD

**Issue by Zinelaabidine** [onosproject/onos-config#1364]
When installing µONOS using the helm charts in a Kubernetes cluster with KubeOVN CNI. I got Init: CrashLoopBackOff in the onos-config-XXX-XXX pod. All the four containers of this pod were waiting for the Init-container model-registry-init. 
```
 Every 2.0s: kubectl get pod -A                                                                                vim: Tue Oct 26 13:02:38 2021
NAMESPACE     NAME                                              READY   STATUS                  RESTARTS        AGE
kube-system   atomix-controller-6767f468cc-4q6gn                1/1     Running                 0               7m43s
kube-system   atomix-raft-storage-controller-7c94f786cb-ldv2n   1/1     Running                 0               7m19s
kube-system   coredns-78fcd69978-hjgz5                          1/1     Running                 0               3h18m
kube-system   coredns-78fcd69978-zwmqn                          1/1     Running                 0               3h18m
kube-system   etcd-vim                                          1/1     Running                 0               3h20m
kube-system   kube-apiserver-vim                                1/1     Running                 0               3h19m
kube-system   kube-controller-manager-vim                       1/1     Running                 0               3h19m
kube-system   kube-ovn-cni-52pv2                                1/1     Running                 0               3h12m
kube-system   kube-ovn-cni-p2sg8                                1/1     Running                 0               7h41m
kube-system   kube-ovn-controller-86b5d98495-67x7c              1/1     Running                 3 (3h19m ago)   7h41m
kube-system   kube-ovn-monitor-76958d8497-st6tv                 1/1     Running                 0               7h40m
kube-system   kube-ovn-pinger-75tc6                             1/1     Running                 0               7h40m
kube-system   kube-ovn-pinger-gtsth                             1/1     Running                 0               3h12m
kube-system   kube-proxy-2dgh8                                  1/1     Running                 0               3h12m
kube-system   kube-proxy-8sfww                                  1/1     Running                 0               3h18m
kube-system   kube-scheduler-vim                                1/1     Running                 0               3h18m
kube-system   onos-operator-app-585d588d5c-q9785                1/1     Running                 0               6m40s
kube-system   onos-operator-config-6d59c87b9b-f9lcp             1/1     Running                 0               6m40s
kube-system   onos-operator-topo-7ff4df6f57-68hvx               1/1     Running                 0               6m40s
kube-system   ovn-central-58758d76c9-zg7m9                      1/1     Running                 0               7h41m
kube-system   ovs-ovn-7rlhl                                     1/1     Running                 0               7h41m
kube-system   ovs-ovn-nbtv4                                     1/1     Running                 0               3h12m
micro-onos    onos-cli-75576b4d48-4rjjw                         1/1     Running                 0               2m48s
micro-onos    onos-config-69776577fd-zz6td                      0/4     Init:CrashLoopBackOff   2 (20s ago)     2m47s
micro-onos    onos-consensus-store-0                            1/1     Running                 0               2m47s
micro-onos    onos-gui-847f99659-mvh7n                          2/2     Running                 0               2m48s
micro-onos    onos-topo-7d79d4b7cd-fsqg8                        3/3     Running                 0               2m48s
```

when inspecting this container (model-registry-init) I got 

```
2021-10-26T06:46:02.111Z INFO config-model/plugin/module module/resolver.go:157 Fetching module 'github.com/onosproject/onos-config@v0.9.3'
go get: github.com/onosproject/onos-config@v0.9.3: Get "https://proxy.golang.org/github.com/onosproject/onos-config/@v/v0.9.3.info": dial tcp 216.58.211.17:443: i/o timeout
2021-10-26T06:46:32.143Z ERROR config-model/plugin/module module/resolver.go:181 Failed to fetch module 'github.com/onosproject/onos-config@v0.9.3': exit status 1
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).fetchMod
/onos-config-model/pkg/model/plugin/module/resolver.go:181
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).Resolve
/onos-config-model/pkg/model/plugin/module/resolver.go:120
main.getInitCmd.func1
/onos-config-model/cmd/config-model/main.go:82
github.com/spf13/cobra.(*Command).execute
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
/onos-config-model/cmd/config-model/main.go:52
runtime.main
/usr/local/go/src/runtime/proc.go:225
2021-10-26T06:46:32.144Z ERROR config-model config-model/main.go:84 Failed to initialize module 'github.com/onosproject/onos-config@v0.9.3': exit status 1
main.getInitCmd.func1
/onos-config-model/cmd/config-model/main.go:84
github.com/spf13/cobra.(*Command).execute
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
/onos-config-model/cmd/config-model/main.go:52
runtime.main
/usr/local/go/src/runtime/proc.go:225
Error: exit status 1
(0x134e780,0xc00011ae20)
exit status 1
```

**Comment by sunil-parida** [comment]
we also observing same issue on  calico-cni  kubernetes deployment environment
can we get fix for calico-cni

smartedge-open@esi69:~$ kubectl -n sdran get pod
NAME                             READY   STATUS                  RESTARTS      AGE
onos-cli-764d9697fb-wjz7g        1/1     Running                 0             56m
onos-config-69cf8b888c-8wgzs     0/4     Init:CrashLoopBackOff   9 (46s ago)   28m
onos-consensus-store-0           1/1     Running                 0             56m
onos-e2t-df496c8cd-4gkqj         3/3     Running                 0             56m
onos-mho-5d874cbf7c-4z2b6        2/2     Running                 1 (55m ago)   67m
onos-topo-79f7c5c54d-qstgq       3/3     Running                 0             56m
onos-uenib-6f7466c87f-628jk      3/3     Running                 0             56m
ran-simulator-69bfbb46bd-tw28f   1/1     Running                 0             56m
smartedge-open@esi69:~$


smartedge-open@esi69:~$ kubectl -n sdran logs onos-config-69cf8b888c-8wgzs -c model-registry-init
2021-11-03T17:40:47.500Z        INFO    config-model/plugin/module      module/resolver.go:157  Fetching module 'github.com/onosproject/onos-config@v0.9.4'
go get: github.com/onosproject/onos-config@v0.9.4: Get "https://proxy.golang.org/github.com/onosproject/onos-config/@v/v0.9.4.info": dial tcp 142.250.195.113:443: i/o timeout
2021-11-03T17:41:17.542Z        ERROR   config-model/plugin/module      module/resolver.go:181  Failed to fetch module 'github.com/onosproject/onos-config@v0.9.4': exit status 1
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).fetchMod
        /onos-config-model/pkg/model/plugin/module/resolver.go:181
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).Resolve
        /onos-config-model/pkg/model/plugin/module/resolver.go:120
main.getInitCmd.func1
        /onos-config-model/cmd/config-model/main.go:82
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /onos-config-model/cmd/config-model/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:225
Error: exit status 1
(0x134e780,0xc00039b600)
2021-11-03T17:41:17.543Z        ERROR   config-model    config-model/main.go:84 Failed to initialize module 'github.com/onosproject/onos-config@v0.9.4': exit status 1
main.getInitCmd.func1
        /onos-config-model/cmd/config-model/main.go:84
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /onos-config-model/cmd/config-model/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:225
exit status 1
smartedge-open@esi69:~$

**Comment by sunil-parida** [comment]
`we also observing same issue on  calico-cni  kubernetes deployment environment
can we get fix for calico-cni

smartedge-open@esi69:~$ kubectl -n sdran get pod
NAME                             READY   STATUS                  RESTARTS      AGE
onos-cli-764d9697fb-wjz7g        1/1     Running                 0             56m
onos-config-69cf8b888c-8wgzs     0/4     Init:CrashLoopBackOff   9 (46s ago)   28m
onos-consensus-store-0           1/1     Running                 0             56m
onos-e2t-df496c8cd-4gkqj         3/3     Running                 0             56m
onos-mho-5d874cbf7c-4z2b6        2/2     Running                 1 (55m ago)   67m
onos-topo-79f7c5c54d-qstgq       3/3     Running                 0             56m
onos-uenib-6f7466c87f-628jk      3/3     Running                 0             56m
ran-simulator-69bfbb46bd-tw28f   1/1     Running                 0             56m
smartedge-open@esi69:~$


smartedge-open@esi69:~$ kubectl -n sdran logs onos-config-69cf8b888c-8wgzs -c model-registry-init
2021-11-03T17:40:47.500Z        INFO    config-model/plugin/module      module/resolver.go:157  Fetching module 'github.com/onosproject/onos-config@v0.9.4'
go get: github.com/onosproject/onos-config@v0.9.4: Get "https://proxy.golang.org/github.com/onosproject/onos-config/@v/v0.9.4.info": dial tcp 142.250.195.113:443: i/o timeout
2021-11-03T17:41:17.542Z        ERROR   config-model/plugin/module      module/resolver.go:181  Failed to fetch module 'github.com/onosproject/onos-config@v0.9.4': exit status 1
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).fetchMod
        /onos-config-model/pkg/model/plugin/module/resolver.go:181
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).Resolve
        /onos-config-model/pkg/model/plugin/module/resolver.go:120
main.getInitCmd.func1
        /onos-config-model/cmd/config-model/main.go:82
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /onos-config-model/cmd/config-model/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:225
Error: exit status 1
(0x134e780,0xc00039b600)
2021-11-03T17:41:17.543Z        ERROR   config-model    config-model/main.go:84 Failed to initialize module 'github.com/onosproject/onos-config@v0.9.4': exit status 1
main.getInitCmd.func1
        /onos-config-model/cmd/config-model/main.go:84
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /onos-config-model/cmd/config-model/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:225
exit status 1
smartedge-open@esi69:~$
`

**Comment by sunil-parida** [comment]
We are  also observing same issue on  calico-cni  kubernetes deployment environment
can we get fix for calico-cni


$ kubectl -n sdran get pod
NAME                             READY   STATUS                  RESTARTS      AGE
onos-cli-764d9697fb-wjz7g        1/1     Running                 0             56m
onos-config-69cf8b888c-8wgzs     0/4     Init:CrashLoopBackOff   9 (46s ago)   28m
onos-consensus-store-0           1/1     Running                 0             56m
onos-e2t-df496c8cd-4gkqj         3/3     Running                 0             56m
onos-mho-5d874cbf7c-4z2b6        2/2     Running                 1 (55m ago)   67m
onos-topo-79f7c5c54d-qstgq       3/3     Running                 0             56m
onos-uenib-6f7466c87f-628jk      3/3     Running                 0             56m
ran-simulator-69bfbb46bd-tw28f   1/1     Running                 0             56m
$



$ kubectl -n sdran logs onos-config-69cf8b888c-8wgzs -c model-registry-init
2021-11-03T17:40:47.500Z        INFO    config-model/plugin/module      module/resolver.go:157  Fetching module 'github.com/onosproject/onos-config@v0.9.4'
go get: github.com/onosproject/onos-config@v0.9.4: Get "https://proxy.golang.org/github.com/onosproject/onos-config/@v/v0.9.4.info": dial tcp 142.250.195.113:443: i/o timeout
2021-11-03T17:41:17.542Z        ERROR   config-model/plugin/module      module/resolver.go:181  Failed to fetch module 'github.com/onosproject/onos-config@v0.9.4': exit status 1
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).fetchMod
        /onos-config-model/pkg/model/plugin/module/resolver.go:181
github.com/onosproject/onos-config-model/pkg/model/plugin/module.(*Resolver).Resolve
        /onos-config-model/pkg/model/plugin/module/resolver.go:120
main.getInitCmd.func1
        /onos-config-model/cmd/config-model/main.go:82
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /onos-config-model/cmd/config-model/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:225
Error: exit status 1
(0x134e780,0xc00039b600)
2021-11-03T17:41:17.543Z        ERROR   config-model    config-model/main.go:84 Failed to initialize module 'github.com/onosproject/onos-config@v0.9.4': exit status 1
main.getInitCmd.func1
        /onos-config-model/cmd/config-model/main.go:84
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /onos-config-model/cmd/config-model/main.go:52
runtime.main
        /usr/local/go/src/runtime/proc.go:225
exit status 1
$

**Comment by SeanCondon** [comment]
This seems to be related to the `GOPROXY` setting - more investigation needed
See
https://www.bswen.com/2021/07/others-how-to-solve-golang-issue1.html

**Comment by sunil-parida** [comment]
Hi @SeanCondon  I tryed as suggested GOPROXY setting but no success on our environment..

**Comment by TliliAb** [comment]
@sunil-parida  did you find a solution to this ?

**Comment by sunil-parida** [comment]
> @sunil-parida did you find a solution to this ?

@TliliAb on our environment we are still facing this issue.

**Comment by AbdouTlili** [comment]
@sunil-parida The problem is that the go modules couldn't reach the remote repos from inside the cluster.
- get the name of the calico interface with the command : `ip a | grep calico` in my case it's the interface `vxlan.calico`.

to get your cluster accessing the internet, activate the IP forwarding between the two (your main interface in my case it's `enp4s0` , it can be like `wlp3s0` or similar if you are using wifi).
- you activate the ip forwarding with : 
```
sudo iptables -A FORWARD -i enp4s0 -o vxlan.calico -j ACCEPT
sudo iptables -A FORWARD -i vxlan.calico -o enp4s0 -j ACCEPT 
```
of course you need to change the interfaces in the commands above to match yours.
After this you `helm uninstall -n sdran sd-ran` then re-install it 
``` 
helm install -n sdran sd-ran sdran/sd-ran --set import.ran-simulator.enabled=true --set import.onos-kpimon.enabled=true --version 1.2.0
```

Hope this helps.
Have a great day
