### ISSUE TITLE
Occasional "fatal error: concurrent map writes" on startup

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#156]
Stack trace is in the file on Google Drive
https://drive.google.com/open?id=1-CijAk0WtC12jk3ojhXJJlcFNcFDEMqm

**Comment by Andrea-Campanella** [comment]
I seem to not have access to the file, can you share please ?

**Comment by SeanCondon** [comment]
Should be ok now

**Comment by Andrea-Campanella** [comment]
I'm not seeing this anymore, can we close ?

**Comment by SeanCondon** [comment]
I have not seen it in over a month. I think it has been avoided by the restructuring over time
