### ISSUE TITLE
Use assert package for all unit tests to make the code more readable 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#169]
Some of the unit tests use assert for comparing expected values to actual values and some of them not. So we should use "assert" package for all of the unit tests as much as possible.

**Comment by adibrastegarnia** [comment]
You can assign it to me and I will take care of them.

**Comment by Andrea-Campanella** [comment]
Please discuss this with @ray-milkey

**Comment by adibrastegarnia** [comment]
@SeanCondon 

Should we close this as well or keep it open if you want to update other asserts if that is needed?

**Comment by ray-milkey** [comment]
I think we can close it.
