### ISSUE TITLE
Pass a Context explicitly to each function - use receiver type functions

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#172]
I think gnmi southbound client manager needs the following changes: 

1. According to the Go documents: Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. So in the clientmanager implementation the context should be passed to the functions which need it. 

2. We should use the receiver pointer and value functions to avoid sending target as an argument to the functions.

**Comment by tomikazi** [comment]
I'd retitle to be more specific (to give a better idea from the issue's list)

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia I think you had a patch for this on the previous enos-config repo living under opennetworkinglab. Coudl you move it over to hear ? thanks!

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 
Yes. My plan is to open a pull request soon and you can review it from there.

**Comment by adibrastegarnia** [comment]
closed #183
