### ISSUE TITLE
devicesim using GNXI project's gnmi_target does not support Subscribe

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#212]
See https://github.com/google/gnxi/blob/master/gnmi/server.go line 623

Also when I try calling Subscribe I do not get this error message. Use the following to see it in action

```
gnmi_cli -address localhost:10161 \
-proto "subscribe:<mode: 0, prefix:<>, subscription:<path: <elem: <name: 'openconfig-system:system'> elem: <name: 'clock' > elem: <name: 'config'> elem: <name: 'timezone-name'>>>>" \
-timeout 5s -alsologtostderr \
-client_crt certs/client1.crt \
-client_key certs/client1.key \
-ca_crt certs/onfca.crt
```

**Comment by adibrastegarnia** [comment]
We can add it in gnmi target code and overwrites. I will talk about it today.

**Comment by adibrastegarnia** [comment]
@SeanCondon @tomikazi @ray-milkey @Andrea-Campanella @kuujo 

The changes that we need to made at this point are:

1- We need to return an error message to the client from gnmi target
2- We need to support subscribe. 

By looking at the code, *gnmi_target.go* which implement the target uses the *server.go* under gnmi directory in gnxi tool github repository and they overwrite Get and Set functions to provide user authentication. That means for now we just need to have gnmi_target.go in onos-config repo to support the features that we are looking for without touching the *server.go* code. 

To do that, we need to create a directory called third_party under onos-config to have gnmi_target package there. We will change Docker file later to fetch it from our repo.

**Comment by SeanCondon** [comment]
Adib - I think you can put it in tools/test/devicesim/gnmi_target.
I wouldn't call it third_party because we're copying the code once off with no further reference to gnxi. We did something similar with utils from Arista

**Comment by adibrastegarnia** [comment]
@SeanCondon 
OK. I will do that and open a initial pull request soon.

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia move this issue to the simulator repo and then close

**Comment by adibrastegarnia** [comment]
@SeanCondon  @Andrea-Campanella 

Please close this issue. I cannot close it.
