### ISSUE TITLE
gNMI Path validation 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#227]
After a little bit thinking about this problem, the best approach to address that is to extend *gNMIPathUtils.go* to add path validation (which is also mentioned as a TODO) function that we can use it in devicesim and also in other packages if it is required (e.g. NB). For example, in the devicesim we can use the validation function to validate a path and if the path is invalid then the function which called validation function returns an invalid path error to the client. Please let me know what do you think?

**Comment by SeanCondon** [comment]
I think this is mixing up the priorities and may only lead to future problems. Path validation on the NB will be very complex and driven by a dynamic set of YANG models.
Path validation on the devicesim needs a few very simple specific use cases for the moment - remember it is just a test tool.
In future we may have a model driven devicesim, but each instance will only have to tackle one model (and one version of it) at a time, whereas onos-config will have to handle many models of different versions at a time.
There is a case for simple path syntax validation - I think this is taken care of by the regexp in configvalue.go

**Comment by Andrea-Campanella** [comment]
+1 with Sean here. I think the design of the Yang toolchain and path validation needs to be done properly taking into account different aspect. Thus this topic requires further discussion.

**Comment by adibrastegarnia** [comment]
You are right. Thanks for your comments.
