### ISSUE TITLE
SetRequest should allow a specific name for a commit

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#228]
Currently when Set is done through gNMI NB, a unique name is generated in our network store (by a hash) for the network change (e.g. *Change-VgUAZI928B644v/2XQ0n24x0SjA=*), as the SetRequest does not provide a field to specifically reference the change.

Since our idea of rollback is based around rolling back a change by *name*, it will be convenient for customers to give their commit a name of their choosing, and have that persisted in the store. I propose to use extension number **101** for this, and will update the documents and use cases. The name will have specific rules - no spaces, **a-z A-Z 0-9**, **_**, **-**, **/**, **=** (the last 2 to allow base64 from the client side)

**Comment by Andrea-Campanella** [comment]
I agree, although I think we shoudl support the case where the extension is not specified. an still generate a name, as convenient as possibile, that can be used for rollback. Thoughts ? 
We should document also our extensions.

**Comment by SeanCondon** [comment]
Of course on both points

**Comment by tomikazi** [comment]
Should we use something similar to the random combos of two-letter words, e.g. crazy-fox, silly-goose, etc. ;)

Thomas

**Comment by SeanCondon** [comment]
Didn't think of that - for the case where user doesn't supply a name
i'll see if there's a go package that generates these - I'm reluctant to depend on an external API for it though - do not want to add external runtime dependencies

**Comment by Andrea-Campanella** [comment]
You might want to look into the docker generator function. Just for fun it has some interesting ban on things like "boring-wozinak" it fails the build with a message like "Wozinak is not boring"

**Comment by tomikazi** [comment]
I completely agree with not adding runtime dependencies. If there is no Go code for this, I know you can find the files/lists of names we can use to randomly permute. Brian did this a while back for some other project.  Reading those files into memory and then combining them (uniquely) should not be much code or be too difficult.

Thomas
