### ISSUE TITLE
Need to store model data per DeviceType in onos-config

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#230]
To support the validation of configuration against YANG models there needs to be a collection of Model data per device type somewhere in onos-config

## Proposal
My proposal is that the DeviceType would be an immutable object containing a sorted set of gnmi.ModelData entries. This would be stored in a store just like Change, Configuration and Network

Each Device would have a name (a tag and a version combined) and an ID (a hash of the model data). Names might be like "Stratum-1.0" or "MyDevice-1.2.3"

The existing Configuration object would be extended to point to a DeviceType.

During connection to the device we could check that the capabilities match the DeviceType preventing us sending down incompatible config to it.

On the NBI this will help validating paths against specific targets. 

It also helps in dealing with multiple versions of devices.

There is a lot more to this, which I will add later, but this is to get the ball rolling

## Alternative
An alternative approach is to extend the Configuration object with an attribute Model []gnmi.Model, so that each configuration holds its own set of Model data

**Comment by Andrea-Campanella** [comment]
with some discussion we think the alternative is best and storing the models with the ModelData Structure

**Comment by tomikazi** [comment]
I like this approach. It provides a nice isolation mechanism for devices with different sets of deviations and augmentations, yet it can take an advantage of homogeneity of devices as well.
