### ISSUE TITLE
Implement subscribe mode for streaming including ON_CHANGE, SAMPLE, and TARGET_DEFINED

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#237]
It looks like in the current implementation when the subscribe function receives a subscribe request, it keeps streaming the updates without checking the subscription mode. So the subscribe function needs enhancements to support that.

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia please always add project and labels to the issues.

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 

I would like to but I can't :) The reason is that only those developers with write access can assign the labels to the issues (https://help.github.com/en/articles/applying-labels-to-issues-and-pull-requests). I can assign labels to the issues in repos that I have write permission. Perhaps there is a workaround for that I don't know. I checked a few other projects and they use ci-robots to add labels automatically (In the long term perhaps we can thing of something similar). I am not sure but perhaps if you setup templates for issues and developers assign the issue to category a default label will be added to the issue. 
Please let me know if I can help on this. 

P.S. We had a discussion about that topic on micro-onos slack if you would like to take a look.

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia my bad, you are correct. Yes, I think we should have a bot to add labels. for now we can also add them by hand while triaging for milestones. 

on another note, yes, this issue needs to be done, but I think it's low priority.

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 

Yes you are correct. Auto-labeling is not important at this moment.

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 

If there is no plan to support subscribe SAMPLE and TARGET_DEFINED, I think we can close this as well.

**Comment by Andrea-Campanella** [comment]
I think we still do have plans to support this as we want to be 100% compliant with gNMI spec, I'll leave it open
