### ISSUE TITLE
Periodic change of operational attribute in devices

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#238]
Implement a periodical change of an attribute in order to test the operational data cache and subscription

**Comment by SeanCondon** [comment]
I think this would be for changing:
```
/system/openflow/controllers/controller/connections/connection/state
```
for a start and not any other config parameters

In future this should look at a container being added or removed

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia move this issue to the simulator repo and then close

**Comment by Andrea-Campanella** [comment]
moved to simulators repo
