### ISSUE TITLE
Remove one layer of registering on NB subscription

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#250]
At the moment we are effectively registering 2 times for updates in the northbound.
the PathToChannels in subscribe.go has to be removed and it's functionality moved down to the listener.go registry mechanism:
filtering is done down at the listener level based on the subscriber string instead with the path at the subscribe.go.
we would need to register one listener per path with register()
Also look into bringing in prefix and target into the subscribe string in the listener.go

**Comment by SeanCondon** [comment]
I think this is fixed now?

**Comment by Andrea-Campanella** [comment]
@SeanCondon no, I was planning to work on that tomorrow. I have a clear idea of what should be done. 
I would greatly benefit from an e2e testing, do you know if ray's work takes care of subscription ?
