### ISSUE TITLE
Unimplemented type STATE on device sim

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#265]
> gnmi_cli -address localhost:10162 \
>        -get \
>        -proto "type: 2" \
>        -timeout 5s -alsologtostderr \
>        -client_crt certs/client1.crt \
>        -client_key certs/client1.key \
>        -ca_crt certs/onfca.crt

returns
```
E0530 15:16:26.582812   49112 gnmi_cli.go:180] target returned RPC error for Get("type:STATE "): rpc error: code = Unimplemented desc = unsupported request type: STATE
```

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 
After implementing subscribe stream, I will look into this.

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia move this issue to the simulator repo and then close

**Comment by adibrastegarnia** [comment]
moved and closed

**Comment by adibrastegarnia** [comment]
> @adibrastegarnia move this issue to the simulator repo and then close

@Andrea-Campanella 
Please close it yourself because I cannot do it.
