### ISSUE TITLE
Unimplemented OPERATIONAL on devicesim

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#266]
> gnmi_cli -address localhost:10162 \
>        -get \
>        -proto "type: 3" \
>        -timeout 5s -alsologtostderr \
>        -client_crt certs/client1.crt \
>        -client_key certs/client1.key \
>        -ca_crt certs/onfca.crt

returns
```
E0530 15:17:14.527324   49113 gnmi_cli.go:180] target returned RPC error for Get("type:OPERATIONAL "): rpc error: code = Unimplemented desc = unsupported request type: OPERATIONAL
```

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia move this issue to the simulator repo and then close

**Comment by adibrastegarnia** [comment]
moved and closed

**Comment by adibrastegarnia** [comment]
> @adibrastegarnia move this issue to the simulator repo and then close

@Andrea-Campanella 
Please close it yourself. I cannot do it.
