### ISSUE TITLE
Rename devicesim on dockerhub to gnmi-device-simulator

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#273]
devicesim is too generic a name for the simulator - should rename to reflect its purpose.

**Comment by adibrastegarnia** [comment]
@SeanCondon 
Since it is likely to expand it to support gNOI in the future as well, perhaps we should think of another name which reflects both or somehow distinguish them.

**Comment by SeanCondon** [comment]
See also #278 for a broader discussion on this

**Comment by Andrea-Campanella** [comment]
@ray-milkey can we close or move to the simulators repo ?

**Comment by ray-milkey** [comment]
Leave this open as a reminder to fix the docs once the move is complete.

**Comment by ray-milkey** [comment]
Docs are fixed, old docker hub repo is gone, closing this,
