### ISSUE TITLE
Split Run.md into different files.

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#279]
Currently Run.md is getting long and cluttered
I Propose to separate this into:

- run
- gnmi
- admin
- diagnostics

**Comment by adibrastegarnia** [comment]
+1

**Comment by tomikazi** [comment]
That sounds good, except I'd suggest that the top-level run has a simple usage of running the server, simple gnmi_cli and a simple admin to show the basics. It can then frame branching into the more detailed individual sections.
