### ISSUE TITLE
For CLI tools (admin/diag) we ought to consider common primary, e.g. 'onos ...'

### ISSUE THREAD

**Issue by tomikazi** [onosproject/onos-config#280]
Down the road, we may want to consider doing what git, k8s, helm and other projects are doing  with respect to their command line clients: have a common root command. For example

- onos changes [options]
- onos net-changes [options]
- onos devices|links|hosts [options]
- ...

This is not urgent, but we may want to consider how this would work across the onos-config, onos-control, etc. projects

**Comment by tomikazi** [comment]
We should use https://github.com/spf13/cobra. Having a common root may require that we setup CLI commands to be implemented in their own project/repository.

**Comment by adibrastegarnia** [comment]
@tomikazi 

If you need help on that, I would be happy to help. It looks straightforward to setup cobra for onos-config project.

**Comment by kuujo** [comment]
FYI it only took me a day to implement the entire CLI for Atomix:
https://github.com/atomix/atomix-go-client/tree/master/pkg/cli

I’d suggest at least creating it initially in onos-config and then moving it elsewhere. That makes it much easier to iterate on the code structure and figure out the patterns that need to be used in future projects.

**Comment by Andrea-Campanella** [comment]
+1 on creating it in onos-config for now, we can split it out later. We shoudl standby the fact that somebody want just onos-config he should be able to deploy only that (+ Topo)

**Comment by tomikazi** [comment]
That sounds good to me!

Thomas
