### ISSUE TITLE
Format the JSON in gNMI replies according to RFC 7951

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#295]
When a gNMI GetResponse is generated with a JSON value this should be formatted according to RFC 7951

See example at https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/prog/configuration/168/b_168_programmability_cg/gNMI_protocol.html

this is currently done through tree.go. An investigation is need to see if this is available in an open source function, and if what tree.go is doing it correctly

**Comment by adibrastegarnia** [comment]
@SeanCondon 

Ygot has that functionality which is used in the simulator as well to build a jsontree : 

ygot.ConstructIETFJSON(nodeStruct, &ygot.RFC7951JSONConfig{AppendModuleName: true})
