### ISSUE TITLE
Subscribe stream NB improvements 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#314]
**Is your feature request related to a problem? Please describe.**
I think subscribe stream in the northbound needs to be refactored. Currently, a go routine started to stream events when the server initialized. I don't think that is  correct to make this assumption that user will need subscription stream in future. The process of handling subscribe stream requests should be created when we receive a subscribe stream request and it should be called inside subscribe function. If my understanding is correct from what I see, it is isolated from subscribe implementation. 

**Describe the solution you'd like**
subscribe stream requests should be handled inside the subscribe function. 

Just my two cents!

**Comment by SeanCondon** [comment]
Can you be more specific with line numbers and file names? Is this coming from some template?

**Comment by adibrastegarnia** [comment]
Hi Sean, 

There is no template as such to follow but gnmi subscribe reference implementation is one starting point (https://github.com/openconfig/gnmi/blob/master/subscribe/subscribe.go).  I implemented the subscribe stream in the simulator without making the subscribe stream isolated from other subscriptions (i.e. once and poll). To give you a reference in the code:
under northbound/gnmi/subscribe.go the following function is responsible to get changes from change store and send it to the client who subscribed to receive events. This function is started as a go routine in the service.go. 

func broadcastConfigNotification() {
}

 That means even when we don't have any subscribe stream request coming we started a process to listen to the changes and stream events. My point is that why don't we handle it like subscribe once and poll in the subscribe function?

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia I already have an issue to simplify the NB streaming, #277, closing this one.
