### ISSUE TITLE
Make Dispatcher and events more generic  and type independent

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#315]
**Is your feature request related to a problem? Please describe.**
We should have one function (lets call it handlers) that takes care of handling the events independent of type. In the current implementation, we have a separate handler for each type. Also type of values in the event should be changed from map to interface to support any type. 

**Describe the solution you'd like**
To avoid having multiple handlers to handle different types of events, we need to register each event which allows us to implement a single handler. That means when we register the listener, we will take care of type of the event and make sure the event is already registered. Here is an implementation that is  used in the simulators repo:

https://github.com/onosproject/simulators/blob/master/pkg/dispatcher/dispatcher.go
https://github.com/onosproject/simulators/blob/master/pkg/events/events.go

Just my two cents!

**Comment by SeanCondon** [comment]
I had been tempted to do this, but I found it hard to justify the effort. I felt I would rather put the effort in to making the code more readable and understandable - like having stronger type checking. Can you explain who this proposed change benefits and how?

**Comment by adibrastegarnia** [comment]
Hi Sean, 

  I think what I proposed make the code more readable, understandable and standard. In the current implementation, for every event we need to define a map instead of making the handler type independent. In my opinion, the current implementation is not standard (i.e. doesn't follow the best practices of a implementing of an event distribution mechanism) and thread safe. Before implementing the dispatcher for simulator, I read about it and compared different solutions and picked the best one which also uses go features (i.e. reflect). Again just my two cents!

**Comment by Andrea-Campanella** [comment]
there was a generic type Event before but that got split into different type. I don't see a proliferation of events. I actually pretty confident that we won't need to add any other type, thus the benefits of using reflection and other mechanism would go against readability, simplicity and speed.
