### ISSUE TITLE
At startup if one of the devices listed in deviceStore is not contactable others halt

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#322]
On startup of onos-config the system will try to connect to all of the devices in deviceStore.
Currently there are 4 devices
* 3 devicesim simulators
* 1 stratum device (localhost:50001)

The synchronizer factory can try connecting to these in any order - if one can't be contacted though the others can't proceed, meaning that there is behavior each time you start onos-config

**Comment by Andrea-Campanella** [comment]
As per our discussion factory.go should spawn a routine passing an error channel to give back errors and timeouts.

**Comment by Andrea-Campanella** [comment]
when #332 is merged we can close this in favour of the #333
