### ISSUE TITLE
Docker image build hangs and fails on go test

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#354]
**Describe the bug**
When running `make images`, the `onos-config` Docker build consistently fails for me on the master branch. It fails at different points during `go test` (examples below).

**To Reproduce**
1. Pull `master`
2. Run `make images`
3. Repeat if necessary

**Expected behavior**
No error :-)

**Screenshots**

```
go test github.com/onosproject/onos-config/pkg/...
?   	github.com/onosproject/onos-config/pkg	[no test files]
The command '/bin/sh -c cd /go/src/github.com/onosproject/onos-config && make build' returned a non-zero code: 137
make: *** [onos-config-docker] Error 137
```

```
go test github.com/onosproject/onos-config/pkg/...
?   	github.com/onosproject/onos-config/pkg	[no test files]
?   	github.com/onosproject/onos-config/pkg/certs	[no test files]
?   	github.com/onosproject/onos-config/pkg/cli	[no test files]
?   	github.com/onosproject/onos-config/pkg/cli/command	[no test files]
ok  	github.com/onosproject/onos-config/pkg/dispatcher	0.018s
ok  	github.com/onosproject/onos-config/pkg/events	0.238s
ok  	github.com/onosproject/onos-config/pkg/manager	0.119s
?   	github.com/onosproject/onos-config/pkg/northbound	[no test files]
The command '/bin/sh -c cd /go/src/github.com/onosproject/onos-config && make build' returned a non-zero code: 137
make: *** [onos-config-docker] Error 137
```

**Comment by kuujo** [comment]
FYI this is no longer a blocker. It appears there's a race condition in tests that becomes highly likely to cause problems when the Docker daemon is already consuming a lot of CPU (e.g. running a lot of k8s/kind containers). But it _is_ an issue AFAICT so we should keep this open.

**Comment by SeanCondon** [comment]
When this runs normally the next to be tested is
- github.com/onosproject/onos-config/pkg/northbound/admin
which means it's likely that's where is stalling
