### ISSUE TITLE
Unmarshalling error

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#357]
**Describe the bug**

**To Reproduce**
1. ```go run github.com/onosproject/onos-config/cmd/onos-config     -configStore=$HOME/go/src/github.com/onosproject/onos-config/configs/configStore-sample.json     -changeStore=$HOME/go/src/github.com/onosproject/onos-config/configs/changeStore-sample.json     -deviceStore=$HOME/go/src/github.com/onosproject/onos-config/configs/deviceStore-sample.json     -networkStore=$HOME/go/src/github.com/onosproject/onos-config/configs/networkStore-sample.json     -modelPlugin=$HOME/go/src/github.com/onosproject/onos-config/modelplugin/TestDevice-1.0.0/testdevice.so.1.0.0     -modelPlugin=$HOME/go/src/github.com/onosproject/onos-config/modelplugin/TestDevice-2.0.0/testdevice.so.2.0.0     -modelPlugin=$HOME/go/src/github.com/onosproject/onos-config/modelplugin/Devicesim-1.0.0/devicesim.so.1.0.0```
2. ```gnmi_cli -address localhost:5150 -set     -proto "update: <path: <target: 'localhost-1', elem: <name: 'openconfig-system:system'> elem: <name: 'clock' > elem: <name: 'config'> elem: <name: 'timezone-name'>> val: <string_val: 'Europe/Paris'>>"     -timeout 5s -alsologtostderr     -client_crt pkg/southbound/testdata/client1.crt     -client_key pkg/southbound/testdata/client1.key     -ca_crt pkg/southbound/testdata/onfca.crt```
3. See error

**Expected behavior**

**Screenshots**
2019/06/14 16:11:48 Added change 8n0PlTklkfRHM3vDlWpHqvcnQSA= to ChangeStore (in memory)
panic: Cannot unmarshal JSON: unmarshalLeafList for schema authentication-method: value openconfig-aaa-types:LOCAL (string): got type string, expect []interface{}

goroutine 26 [running]:
github.com/onosproject/onos-config/modelplugin/Devicesim-1%2e0%2e0.modelplugin.UnmarshalConfigValues(0x0, 0x0, 0xc000101000, 0x39a, 0x400, 0xc000210540, 0x45479a0, 0xc000210540)
	/Users/andrea/go/src/github.com/onosproject/onos-config/modelplugin/Devicesim-1.0.0/modelmain.go:45 +0x18e
github.com/onosproject/onos-config/pkg/manager.(*Manager).SetNetworkConfig(0x4aea4e0, 0xc0000e8180, 0x11, 0xc0002103c0, 0x0, 0x0, 0x0, 0x0, 0xc0000f33a0, 0x442c0eb, ...)
	/Users/andrea/go/src/github.com/onosproject/onos-config/pkg/manager/setconfig.go:117 +0xb27
github.com/onosproject/onos-config/pkg/northbound/gnmi.(*Server).buildUpdateResults(0xc000176e80, 0xc0000f3828, 0xc0002d77f8, 0x0, 0x0, 0x0, 0x0, 0xc0002e4038, 0x0, 0x0, ...)
	/Users/andrea/go/src/github.com/onosproject/onos-config/pkg/northbound/gnmi/set.go:170 +0x1e9
github.com/onosproject/onos-config/pkg/northbound/gnmi.(*Server).Set(0xc000176e80, 0x46ce900, 0xc0002100f0, 0xc000452000, 0x0, 0x0, 0x0)
	/Users/andrea/go/src/github.com/onosproject/onos-config/pkg/northbound/gnmi/set.go:85 +0xad0
github.com/onosproject/onos-config/vendor/github.com/openconfig/gnmi/proto/gnmi._GNMI_Set_Handler(0x45a6960, 0xc000176e80, 0x46ce900, 0xc0002100f0, 0xc000562370, 0x0, 0x46ce900, 0xc0002100f0, 0xc00001e000, 0x67)
	/Users/andrea/go/src/github.com/onosproject/onos-config/vendor/github.com/openconfig/gnmi/proto/gnmi/gnmi.pb.go:2671 +0x23e
github.com/onosproject/onos-config/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00020e780, 0x46d4620, 0xc00042d800, 0xc000278300, 0xc000210a80, 0x4ade450, 0x0, 0x0, 0x0)
	/Users/andrea/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:972 +0x470
github.com/onosproject/onos-config/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00020e780, 0x46d4620, 0xc00042d800, 0xc000278300, 0x0)
	/Users/andrea/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:1252 +0xda6
github.com/onosproject/onos-config/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000c76e0, 0xc00020e780, 0x46d4620, 0xc00042d800, 0xc000278300)
	/Users/andrea/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:691 +0x9f
created by github.com/onosproject/onos-config/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/andrea/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:689 +0xa1
exit status 2

**Comment by SeanCondon** [comment]
This happens because the validation of the Devicesim configurations are not done until the first attempt is made to change an attribute on one of the devices like this - and then it all blows up :-(

Even when validation is done at startup there are still 2 problems that need to be tackled:
1) The json generated represents the **authentication-method** attribute like 
```
"authentication-method": "openconfig-aaa-types:LOCAL"
```
but because it is a **leaf list** the value should be like
```
"authentication-method": ["openconfig-aaa-types:LOCAL"]
```

For this reason the YGot Marshaller throws this error: 
```
panic: Cannot unmarshal JSON: unmarshalLeafList for schema authentication-method: value openconfig-aaa-types:LOCAL (string): got type string, expect []interface{}
```

The question is how to deal with this type of thing - there is no way of knowing from a simple string value that the type should be leaf-list - this can only be inferred from the Schema.

Further investigation is needed. This is not the only such case - the **aux-id** expects to be a **float64**
