### ISSUE TITLE
modelmain.go without main function

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#361]
**Describe the bug**
modelmain.go  files are main packages but there is no sign of main function in the code. I am not sure how you build it but I cannot. 

**Additional context**
I think func main() {} should be added to the code.

**Comment by SeanCondon** [comment]
This is a plugin (clue is in the name). See line 28 of run.md

**Comment by adibrastegarnia** [comment]
@SeanCondon 
Yes I am aware of that. I found out why it works because we build each main package in the cmd separately. If we build the whole project go build -v ./... then go cannot distinguish those are plugings. Thanks for your response.
