### ISSUE TITLE
enable logs capturing before tearing down the onit cluster

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#418]
**Is your feature request related to a problem? Please describe.**
Currently the state of the logs and the cluster disappears when `onit delete cluster` is issued.

**Describe the solution you'd like**
We should capture the logs and save them somewhere so we can look at them at any given time,

**Comment by kuujo** [comment]
@ray-milkey where would we want to write logs to? The current directory by default I suppose?
