### ISSUE TITLE
Enable get on operational state cache

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#419]
**Is your feature request related to a problem? Please describe.**
Currently the northbound get only check the config store and not the operational state cache which is built with operational and state information out of the device

**Describe the solution you'd like**
we should make the get point to the cache also to make sure to retrieve the latest information about state or operational values.

**Comment by SeanCondon** [comment]
First a mechanism to extract config=false elements from the schema of the model plugin will need to be put in place. I will do this in a separate issue
