### ISSUE TITLE
onit cannot create cluster on Ubuntu (microk8s) - onos-config-debug fails

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#481]
**Describe the bug**
Running **onit create cluster** on Ubuntu with microk8s fails because running the docker image **onos-config-debug** without **--security-opt seccomp:unconfined** means that **onos-config-debug** can't start

**To Reproduce**
After running **make images** on Ubuntu try running the docker image **onosproject/onos-config:debug** like, and watch it fail:
```
$ docker run -it onosproject/onos-config:debug 
API server listening at: [::]:40000
could not launch process: fork/exec /usr/local/bin/onos-config: operation not permitted
$
```

**Expected behavior**
Now try running it with:
```
$ docker run -it --security-opt seccomp:unconfined onosproject/onos-config:debug 
API server listening at: [::]:40000
```
and see how it runs properly.

This should also be applied to how **onit** runs this Docker image

**Additional context**
In **createOnosConfigDeployment()** of **test/runner/onos-config.go**, the PodSecurityPolicy should have the annotation added like:
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp

**Comment by kuujo** [comment]
The k8s documentation suggests `seccomp:unconfined` is the default:
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp

**Comment by kuujo** [comment]
Maybe it's the default only if a `PodSecurityPolicy` is added... but that requires non-trivial setup to the cluster itself to enable support for `PodSecurityPolicy`s

**Comment by kuujo** [comment]
The above PR should fix the issue. A `PodSecurityPolicy` doesn't seem the right way to specify security options on a pod because `PodSecurityPolicy` is designed as a filter to prevent insecure pods from being scheduled. The original proposal documents showed instead the `seccomp.security.alpha.kubernetes.io/pod` annotation which should allow the profile to be set for the pod.

@SeanCondon what k8s version are you using? `kubectl version`

**Comment by SeanCondon** [comment]
1.15.0
```
scondon@Z420:/RaidData/scondon/onos$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
scondon@Z420:/RaidData/scondon/onos$ 
```

**Comment by SeanCondon** [comment]
This does not appear to be an issue with KinD - only with microk8s
