### ISSUE TITLE
Change Key of ChangeStore to change.ID

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#486]
**Is your feature request related to a problem? Please describe.**
Currently the ChangeStore uses a string key but we have a change.ID object that is designed precisely to identify a change.

**Describe the solution you'd like**
They type of the key of the ChangeStore should be changed to change.ID

**Comment by SeanCondon** [comment]
The key of the Change store uses a string as a key
change
**map[string]\*change.Change**
to 
**map[change.ID]\*change.Change**

**Comment by tomikazi** [comment]
I don't believe this is possible as `type ID []byte` does not meet the strict key requirements for maps in Go.

**Comment by kuujo** [comment]
This will work for a type derived from a string.

But I think this might be a little premature. The stores will make this particular key obsolete in the next couple weeks. But with respect to the idea of the change for other parts of the code, that may be premature as well. Distributed stores will require primitives that are Protobuf generate message types, so their IDs and other fields will be limited Protobuf types which are roughly the same as Golang primitive types. Sure, we could pass around casted types, but their underlying representation will still be a primitive type so I’m not sure there’s a lot of benefit. One thing we could do is convert Protobuf generated messages to structs with more meaningful types, but that is costly in both performance and maintenance overhead, so I’m advocating for using Protobuf generated types directly whenever possible (remember we can add receivers to generated structs as well).

**Comment by SeanCondon** [comment]
yes - i hadn't realized the complexity with []byte - not a simple substitution. Closing because this will change with distributed stores
