### ISSUE TITLE
Consolidate string configname and config.ConfigName configname in manager

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#487]
**Is your feature request related to a problem? Please describe.**
Currently Manager obtains the config name either as a string or as config.ConfigName in setconfig, getconfig and rollbackconfig

**Describe the solution you'd like**
Consolidate all the configname parameter type to `config.ConfigName` to avoid casting.

**Comment by tomikazi** [comment]
This looks like it has been finished.
