### ISSUE TITLE
Introduce type check and returning in gNMI subscribe NB

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#493]
**Is your feature request related to a problem? Please describe.**
Currently gNMI subscribe on the NB does not include type checking and return everything as a Json file/string val
See line 215 of subscribe.go
**Describe the solution you'd like**
Subscribe.go needs to be extended in order to include those testing and verification in order to return the proper object type to the client.

**Comment by Andrea-Campanella** [comment]
Check must be done on SubscriptionList at line 44 in Subscribe.go

**Comment by Andrea-Campanella** [comment]
@SeanCondon is this done ?

**Comment by SeanCondon** [comment]
I think it is but am going to keep it open until I can prove it in an integration test
