### ISSUE TITLE
Travis integration test runs having problems in subscribe test again

### ISSUE THREAD

**Issue by ray-milkey** [onosproject/onos-config#512]
Just when I thought this was gone, once again today the tests fail every time. I have seen it on local runs several times too:

onit run suite integration-tests
 ✓ Starting test job: test-2634377703
=== RUN   single-path
--- PASS: single-path (0.07s)
=== RUN   subscribe
--- FAIL: subscribe (0.10s)
    subscribetest.go:111: 
        	Error Trace:	subscribetest.go:111
        	Error:      	Expected Update Response
        	Test:       	subscribe
FAIL
make: *** [integration] Error 1
The command "make integration" exited with 2.

**Comment by Andrea-Campanella** [comment]
Apparently the 50 millisecond barrier at line 110 is not enough with clogged systems. I raised that to 1 second in: #515
