### ISSUE TITLE
include an extension to report no yet connected device

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#518]
**Describe the bug**
This issue is based on the experiment which is reported here: #513 . The problem is when there is no device running, the onos-config responds to the requests. For example, in that experiment, we added a device to the device store, configStore, and change Store  but we didn't add a real device using onit add network/simulator. In that scenario, onos-config responds to a get operation with a value which is in the onos-config memory but not coming from the initial configuration in the device. 

**To Reproduce**
See issue #513 

**Expected behavior**
onos-config shouldn't return some values in respond to the requests if there a real device does not exist. It should reply back with a message and inform the user the device doesn't exist.

**Comment by Andrea-Campanella** [comment]
As per our discussion I think it's fine returning some values but in that get response we shoudl have an extension that informs the user that the device is not actually present, thus letting him know that we have stored the configuration and will apply it when/if the device appears.

**Comment by SeanCondon** [comment]
```
onos-config shouldn't return some values in respond to the requests if there a real device does not exist.
```
I would not agree with this completely
1) for config attributes - onos-config should report these values even if device is not there. onos-config is the **master** of the configuration and is always correct
2) for state attributes - yes these should not show if device is disconnected

**Comment by adibrastegarnia** [comment]
> ```
> onos-config shouldn't return some values in respond to the requests if there a real device does not exist.
> ```
> 
> I would not agree with this completely
> 
>     1. for config attributes - onos-config should report these values even if device is not there. onos-config is the **master** of the configuration and is always correct
> 
>     2. for state attributes - yes these should not show if device is disconnected

Yes that makes more sense. Feel free to update the issue if it is needed. I assume that if the device goes down and boots up again with a different config (because of any reason) then onos-config config  will be synced with the device.
