### ISSUE TITLE
Create a python based app to interact with onos-config

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#528]
**Is your feature request related to a problem? Please describe.**
Showcase an example of App interacting with onos-config through the northbound gNMI and Admin interfaces deployed outside or inside the k8s pod.

**Describe the solution you'd like**
A python based application developed completely outside of the onos-config codebase that shows interactions with onos-config via gNMI.
An exampe of auto-generate python bindings can be found here
https://napalm-automation.net/yang-for-dummies/

**Describe alternatives you've considered**
a Go based application was considered but to showcase the multi language power we opted for python

**Comment by SeanCondon** [comment]
Maybe not necessary now ONF Connect is finished

**Comment by Andrea-Campanella** [comment]
@tomikazi ZTP was created in place of this. Closing
