### ISSUE TITLE
Add onos-topo deployment to onit

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#532]
**Is your feature request related to a problem? Please describe.**
Clusters deployed with onit need to be able to use onos-topo. 

**Describe the solution you'd like**
Add deployment of onos-topo nodes in the form of a `Deployment` to onit

**Additional context**
Note this may require some refactoring of the onit `create cluster` parameters. We may need separate `--config-nodes` and `--topo-nodes` parameters.

**Comment by adibrastegarnia** [comment]
Addressed in #578
