### ISSUE TITLE
Improve debugging in onit 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#547]
**Is your feature request related to a problem? Please describe.**
The debugging of containers in onit needs improvements. In addition, we need to document the debugging procedure for the developers. 

**Describe the solution you'd like**
Improve the debugging in onit and add working examples of debugging onos-config-debug in documents.

**Comment by kuujo** [comment]
Yes this should be in the next demo thanks :-)

**Comment by adibrastegarnia** [comment]
I think we can close this since we addressed them at : #551 #546 . In case we need to add more examples, we will refer to it.
