### ISSUE TITLE
Add race detection to automated testing/verification

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#554]
**Is your feature request related to a problem? Please describe.**
We've encountered a few race conditions in tests. We need to use all the tools at our disposal to try to prevent them from being committed in the first place.

**Describe the solution you'd like**
Go provides a race detector 👏
https://golang.org/doc/articles/race_detector.html

Hook it up!

**Comment by adibrastegarnia** [comment]
@kuujo 

At somepoint I was testing it and I observed something and I am not sure it is valid or not yet. I fixed a race condition in the onos-config but the tool was still getting me the warning. We should see if we fix a race condition if the error for that race condition will go away or we need to fix all of them.
