### ISSUE TITLE
Unable to process YANG files via pyang

### ISSUE THREAD

**Issue by tomikazi** [onosproject/onos-config#561]
**Describe the bug**
Attempting to process `modelplugin/yang` files via pyang tool results in the following error:
```
openconfig-aaa@2017-07-06.yang:257: error: extension "openconfig-hashed-value" is not defined in module openconfig-extensions
openconfig-aaa@2017-07-06.yang:325: error: extension "openconfig-hashed-value" is not defined in module openconfig-extensions
FATAL: pyangbind cannot build module that pyang has found errors with.
```

**To Reproduce**
1. Run ```export PYBINDPLUGIN=`python3 -c 'import pyangbind; import os; print ("%s/plugin" % os.path.dirname(pyangbind.__file__));'`;
pyang --plugindir $PYBINDPLUGIN -f pybind openconfig-aaa@2017-07-06.yang```
2. See error

**Expected behavior**
Looking into the openconfig-extensions*.yang file in our source tree, it does not appear to contain definition of the extension `openconfig-hashed-value`, whereas the file on master in the OpenConfig github repo does contain this definition.

**Comment by tomikazi** [comment]
Note that simply adding the following to the `openconfig-extensions*.yang` file will address the issue:
```
  extension openconfig-hashed-value {
      description
        "This extension provides an annotation on schema nodes to
        indicate that the corresponding value should be stored and
        reported in hashed form.
        Hash algorithms are by definition not reversible. Clients
        reading the configuration or applied configuration for the node
        should expect to receive only the hashed value. Values written
        in cleartext will be hashed. This annotation may be used on
        nodes such as secure passwords in which the device never reports
        a cleartext value, even if the input is provided as cleartext.";
    }```

**Comment by SeanCondon** [comment]
@tomikazi there is an explanation at the end of https://github.com/onosproject/onos-config/blob/master/docs/modelplugin.md as to how and why the OpenConfig models were imported. 

The YANG folder is capable of holding many different versions of the OpenConfig models, each one demarcated by date.

The ones in there at the moment are those from the Device Simulator and a good bit older than those used with Stratum (which have not yet been added in).

I was not able to run the command above - I get:
```
scondon@Z420:~/go/src/github.com/onosproject/onos-config/modelplugin/yang$ export PYBINDPLUGIN=`python3 -c 'import pyangbind; import os; print ("%s/plugin" % os.path.dirname(pyangbind.__file__));'`; pyang --plugindir $PYBINDPLUGIN -f pybind openconfig-aaa@2017-07-06.yang
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyangbind'
error pybind: [Errno 2] No such file or directory: 'pybind'
```
To use pyang only the principal YANG files (have a look in Devicesim-1.0.0/modelmain.go to see the list) should be given in the command - others will be imported automatically e.g. to output as a tree:
```
pyang -f tree openconfig-interfaces@2017-07-14.yang openconfig-openflow@2017-06-01.yang openconfig-platform@2016-12-22.yang openconfig-system@2017-07-06.yang
```

Re openconfig-extensions.yang - I will save openconfig-extensions@2017-04-11.yang in to the folder, which removes that error. I did not want to bring the one for master as it would be out of sync with the other yangs for the device simulator

**Comment by tomikazi** [comment]
Thanks Sean! I hadn't realized that this is for the device simulator only and in that case it makes sense to keep the older version to have it in sync with the other parts of the model and simply adding the hashed value extension. Thanks for doing that and for moving the files into their own dirs; that will make it clear that they are only for the simulator.
