### ISSUE TITLE
Include Stratum Yang models 

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#563]
**Is your feature request related to a problem? Please describe.**
Missing stratum Yang models

**Describe the solution you'd like**
Include a model plugin for the stratum Yang models.

**Comment by SeanCondon** [comment]
Please see the Doc 
https://github.com/onosproject/onos-config/blob/master/docs/modelplugin.md

on how to do this. I important thing is to get exactly the versions of the openconfig yang models supported by stratum

**Comment by Andrea-Campanella** [comment]
Closing this as it's done, no deviations but as of now it's ok
