### ISSUE TITLE
Failing docker build on docker hub

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#570]
**Describe the bug**
Currently one of the docker hub build fails with the following log

**To Reproduce**
1. go to commits under onos-config
2. click the Red Cross next to one fo the commits
3. click the details next to the failing docker job

**Expected behavior**
No failure or disabled job because it's useless

**Logs, text or screenshots**
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
Pulling cache layers for index.docker.io/onosproject/onos-config:latest...
Done!
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-3', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-08-30T18:42:30.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'b9a5c95', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-08-30T18:42:30.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-3
MinAPIVersion: 1.12
GitCommit: b9a5c95
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/onosproject/onos-config:latest...
Step 1/10 : ARG ONOS_CONFIG_BASE_VERSION=latest
Step 2/10 : FROM onosproject/onos-config-base:$ONOS_CONFIG_BASE_VERSION as base
manifest for onosproject/onos-config-base:latest not found

**Comment by Andrea-Campanella** [comment]
`ONOS_CONFIG_BASE` does not fine any image because `onos_config_base` is published anywhere

**Comment by Andrea-Campanella** [comment]
@ray-milkey was there any update on this ?

**Comment by ray-milkey** [comment]
No longer relevant
