### ISSUE TITLE
Remove onit related code from onos-config and update Makefile

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#593]
**Is your feature request related to a problem? Please describe.**
After moving onit code successfully, we can start removing onit related code from onos-config repo. 

**Describe the solution you'd like**
Remove test directory and make the changes in the Makefile accordingly.

**Comment by adibrastegarnia** [comment]
We will remove it after Ray updates Travis in onos-test to run tests.

**Comment by Andrea-Campanella** [comment]
@ray-milkey can we close this ?

**Comment by ray-milkey** [comment]
Yes, this is complete.
