### ISSUE TITLE
Expose OpStateCache through gRPC

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#599]
**Is your feature request related to a problem? Please describe.**
Currently the OpStateCahce can't be inspected through and admin/diags interface.

**Describe the solution you'd like**
Admin or Diags should include a new method to expose the OpStateCahce status in detail.

**Comment by SeanCondon** [comment]
It is available through gNMI at present but it would also be very useful to access it through the diags interface (just like **changes** and configs are available).

This would also be useful for the onos-gui as it's easier than having to parse JSON trees.

It would need to have a "subscribe for changes" method too that allowed the GUI (or any other client) to subscribe for all changes on a device through one simple action.

**Comment by SeanCondon** [comment]
This can be implemented in 6 parts 
1) Update github.com/onosproject/onos-config/pkg/northbound/proto/diags.proto with a new **rpc** (in a new OpState service) - GetOpState

2) Update github.com/onosproject/onos-config/pkg/northbound/diags/diags.go with this new Service and a new method. It should retrieve values from manager.OperationalStateCache

3) Update the CLI client at github.com/onosproject/onos-config/pkg/cli/command with a new file opstatecache.go (copy changes.go to get started) and access the gRPC command from 1)

4) Extend diags.go again with a Subscribe method

5) Extend diags.go again for Subscribe

6) Extend CLI again with subscribe
