### ISSUE TITLE
Safe handling of device type/version

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#779]
The documentation for the device type/version extension implies it relies on order:
https://docs.onosproject.org/onos-config/docs/gnmi_extensions/

For example:
> If a version is given where no existing Configuration exists, an error is returned explaining that device type (extension 102 - see below) should also be specified.

> If no extension 101 (version) is given, and only one Configuration already exists for that device (target), then the change is applied to that Configuration.

> If a Configuration already exists for this device name and version and its device type is different to what's given in extension 101, then an error is returned.

Each of these constraints relies on validating a _set_ against the state of the system prior to the _set_. That’s fine in a single-process system that can process requests sequentially, but the only way to do this efficiently in a fault tolerant distributed system is by validating the requests _after_ they’re stored, which is _after_ we have assigned a total order to the requests. Otherwise, its entirely possible a request can be rejected for lack of a type/version even though an “earlier” request already initialized the type/version, or a request can be accepted that should have been rejected.

In some of these cases, we can lazily reject requests without a type or version if the type/version just hasn’t been propagated yet. But the case where the history can switch from one with a single version to one with multiple versions is an obvious race condition that could result in the system essentially having to choose a version for a _set_.

For example:
* A set for device foo version 1.0 is sent to node 1
* A set for device foo version 2.0 is sent to node 2
* Concurrently, more sets for device foo (no version) are sent to both node 1 and node 2

Node 1 might think the sets it received are for version 1.0, and node 2 might think they’re for version 2.0. Iff node 2 happens to have seen version 1.0 or node 1 version 2.0, they might reject the requests. But if they haven’t, they’ll happily write them to the NetworkChange store, in which case any changes that follow the version 1.0 and version 2.0 changes will have to decide which version they apply to. Even querying consistent stores can not eliminate this race condition because time still elapses between querying the stores and accepting a _set_ request.

There are only two ways around this:
* Use consensus to create a total order for the requests (distributed locking before writing to stores) to determine and preserve the state of the system before a request
* Use the total order already assigned to them in stores to validate changes

The former would be extremely and unnecessarily costly considering requests are already written to the stores and validation failures are the exception not the rule. The latter just means validating change types/versions after they’ve been assigned a total order, which is inside controllers. Without doing this, different nodes will see different states at the same time, and validation becomes dependent on which node sees a request and when.

**Comment by kuujo** [comment]
@Andrea-Campanella @SeanCondon

**Comment by SeanCondon** [comment]
Jordan - all valid points you make.

> Use the total order already assigned to them in stores to validate changes

By this I understand you mean all changes (device and network) in the system regardless of state (pending, complete etc).

I agree and think the result should be that the Set() fails if there's *any* doubt over the device name not being present or the version number not being the only one. It will result in more rejections, but I think it's a worthy trade off, since this is an exceptional case and any ambiguity can be avoided by using extensions consistently.

**Comment by Andrea-Campanella** [comment]
Done with DeviceCache
