### ISSUE TITLE
Integration test for single target update/delete in the same request

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#801]
**Is your feature request related to a problem? Please describe.**
Currently we are missing and Integration test for single target update/delete in the same request:

**Describe the solution you'd like**
I'd like a test that is capable of doing
set : <udpate<path/to/elem, value:0>
set : <update<path:a/b/c, value:1>, delete<path/to/elem>>
get : <path<a/b/c>,<path/to/elem>

and endure that there is no value set for path/to/elem while a/b/c is 1

**Comment by ray-milkey** [comment]
Implemented by https://github.com/onosproject/onos-test/commit/c52e499e651f78b040d504943a65351644b0f2fa
