### ISSUE TITLE
Rollbacks implementation issues

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#806]
I think it makes sense to append a new change to roll back an old one. This gives us a complete history of events. But after thinking about how to implement this safely, I realized a couple of issues:

1. Rollbacks must contain a reference to the original change

When the `NetworkChange` controller sees a rollback, it is responsible for ensuring the rollback is applied at the right time/in the correct order. That means ensuring a change is not rolled back before any later change to the device has been rolled back.

https://github.com/onosproject/onos-config/blob/master/pkg/controller/change/network/controller.go#L368

 But in order to make this determination, the controller must know _which_ change is being rolled back and at what time. To do this, the `NetworkChange` for rollbacks must include a reference to the original change ID.

I propose that the `NetworkChange` type use a `oneof` field to specify either a `Change` or a `Rollback`. The `Rollback` would include a reference to the original change being rolled back, and may or may not contain the computed `Change`. That would allow the `NetworkChange` controller to validate rollbacks and ensure they’re run in order.

2. We must differentiate between administrative rollbacks and automatic rollbacks

But appending rollbacks still creates a problem for automatic rollbacks due to partial failures.

First, I want to verify my understanding of the desired behavior is correct:
The sense I got from talking to @SeanCondon is that the failure of an individual device change should essentially never cause a network change to fail. So AIUI, we want a `NetworkChange` to remain enqueued to eventually be applied regardless of the failures that might occur during any single attempt to apply the change. So, in the case where the change is successful on one device but fails on another, we want to roll back the change to ensure we maintain consistency in the network, but following that rollback the change should remain enqueued to be attempted again later. The change will remain enqueued until an administrative rollback. 

https://github.com/onosproject/onos-config/blob/master/pkg/controller/change/network/controller.go#L208

In the case of automatic rollback, the problem is if we append a new change for the rollback without also appending a new change for the retry, we’ll create an erratic ordering of changes and inconsistent state. A change could be followed by multiple automatic rollbacks which would appear to cancel the original change. But to maintain the order of changes, if the controller were to append a new change for each retry, it would also have to append new changes for all later changes to maintain the order of changes.

Because of this, and assuming my understanding of the intended response to failures is correct, I suspect we _don’t_ want to apply a new change in the case of automatic rollbacks. Instead, we can use a third phase - `CANCEL` - to separate an administrative rollback which is permanent and is thus appended to the log from an automatic rollback which is an ephemeral state of the original change.

**Comment by SeanCondon** [comment]
honestly I think the only way to do Rollback with new stores is to **negate** a Network Change as Phase = Rolled Back - which means it is blanked out when you do ExtractFullConfig or Snapshot.

I don't think the Network-Change or Device-Change should persist the delta or that there should be a new NetworkChange for the delta - the delta is only of concern to the actual device and can be calculated at a lower level. Network Changes that are **negated** are still there for trace-ability and logging purposes.

Consider the case where change A add the following 2 paths to 1 device

`/interfaces/interface[name=eth1]/config/name eth1 false`
`/interfaces/interface[name=eth1]/config/enabled UP false`

Before this change there was no interface[name=eth1]
In any delta we would have to make sure that:
`/interfaces/interface[name=eth1]/config/`
`/interfaces/interface[name=eth1]/`
were both deleted.

Then consider a case where there was another change on top of the following existing config:
`/interfaces/interface[name=eth2]/config/name eth2 false`
`/interfaces/interface[name=eth2]/config/enabled UP false`
Change B comes along removing eth2:
`/interfaces/interface[name=eth2]/ -- true`

To roll that back you're going to have to recreate 2 paths (which were not in the original change B)

These examples are just the tip of the iceberg - there can be huge trees of data beneath branches like this

I think the only way to have a clean break is to **negate** the NetworkChange that you want to rollback. Do this by marking it **negated** - not by trying to calculate the reverse.

**Comment by Andrea-Campanella** [comment]
#808 fixes this by doing it at the device level. This implements both administrative rollback and any case where a changed is rolledback in the controllers. Any change that is set to rollback will go down this path and the delta be computed on a per device basis.
@kuujo is there any occasion where the controller does inject ROLLBACK in a change and call update ?

**Comment by SeanCondon** [comment]
I think another scenario that ROLLBACK == *negating the change* supports easily, is where the original change does not have to be in a `COMPLETE` state - its phase could be changed to ROLLBACK before the change has been applied to the real device. In this way it allows a change that causes a problem to be rolled back easily

**Comment by kuujo** [comment]
@Andrea-Campanella there is in one of the LOC I linked:
https://github.com/onosproject/onos-config/blob/master/pkg/controller/change/network/controller.go#L208

The network controller will set device changes to `ROLLBACK` if one of them fails, then sets them back to `CHANGE` `PENDING` once the changes are rolled back. So the `NetworkChange` can only be set to `ROLLBACK` by an administrator, but the `NetworkChange` controller can flip `DeviceChange`s between `CHANGE` and `ROLLBACK` to keep the network consistent.

**Comment by kuujo** [comment]
I think this is a fine approach. The only thing we lose is a totally ordered history of changes/rollbacks, but we can extend the objects to record more useful information about changes/rollbacks later. Kubernetes, for example, stores information indicating why the last _n_ decisions were made (e.g. change failed, rolled back due to partial failure, administrative rollback, etc).

The only weird consistency problem this causes is with validating rollbacks. It’s difficult to tell whether a rollback to change _n_ was requested before change _n+1_ was appended. But I think this is an issue that can be fixed by changing the way versioning/concurrency control is done inside the stores.

**Comment by Andrea-Campanella** [comment]
@kuujo sorry I missed that line. Given this behaviour you described I believe we can close this issue as we don't particularly need the NetworkChange to be set to ROLLBACK other than from the `admin` interface. The device changes will toggle between the states and be applied to the device accordingly. 
@kuujo @SeanCondon Since the changes are then put back in pending state will we try to re-apply them, but maybe we need a mechanism to discern ether error on why it was not applied on the device and do not retry the changes for conditions that we are sure are not transient ?

**Comment by Andrea-Campanella** [comment]
> I think this is a fine approach. The only thing we lose is a totally ordered history of changes/rollbacks, but we can extend the objects to record more useful information about changes/rollbacks later. Kubernetes, for example, stores information indicating why the last _n_ decisions were made (e.g. change failed, rolled back due to partial failure, administrative rollback, etc).
> 
> The only weird consistency problem this causes is with validating rollbacks. It’s difficult to tell whether a rollback to change _n_ was requested before change _n+1_ was appended. But I think this is an issue that can be fixed by changing the way versioning/concurrency control is done inside the stores.

+1 to the weird consistency problem and solution through store versioning, I see it somewhat as a corner case that we can defer, correct ?

**Comment by Andrea-Campanella** [comment]
@kuujo I agree. We would have to define what the list of UNRECOVERABLE errors for a device change are. 
It also depends on other subsystems, e.g if a device loses connection we might receive the notification from topo first because the synchronizer will notify it and the in turn topo to the controller. This might be the case for UNKNOWN and then retry only on notification. @seancondon thoughts ?
