### ISSUE TITLE
Change to logging framework with more granular logging

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#824]
**Is your feature request related to a problem? Please describe.**
The klog library does not support more granular logging levels. Distributed systems components will log massive amounts of data in e.g. benchmarks. 

**Describe the solution you'd like**
We need to be able to do trace/debug logging and control the logging output. We might want to investigate a new logging framework for this reason. The Uber framework supports granular logging and claims exceptional performance:
https://github.com/uber-go/zap

**Describe alternatives you've considered**
As in any language, Go has many logging frameworks. We should take some time to investigate them.

**Additional context**
I intend to experiment with the zap library in Atomix first. Hopefully that can inform this issue.

**Comment by Andrea-Campanella** [comment]
done
