### ISSUE TITLE
Finer grained Topo events filtering in Factory.go

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#843]
**Is your feature request related to a problem? Please describe.**
Currently the factory listens for all Topo events and uses just the ADDED ones to trigger device creation. See Line 39 of factory.go //TODO evaluate the need for fine-grained checking of conditions to connect a device. 

**Describe the solution you'd like**
A more tuned event handling should be considered, allowing for update and administrative disconnection.

**Comment by adibrastegarnia** [comment]
A new version of session management is implemented which employs mastership information. Feel free to open it if you think it is not addressed yet.
