### ISSUE TITLE
Documentation links in the API section do not cross section boundaries

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#901]
**Describe the bug**
Some of the problem here is cross reference between sections

For example in the "ListNetworkChangeResponse" section of the page:
https://docs.onosproject.org/onos-config/docs/api/diags/#onos.config.diags.ListNetworkChangeResponse
there is a link to NetworkChange type which does not work as it only points to
https://docs.onosproject.org/onos-config/docs/api/diags/#onos.config.change.network.NetworkChange
(on the same page).

Instead it should refer to:
https://docs.onosproject.org/onos-config/docs/api/types_change_network/#networkchange

**Comment by adibrastegarnia** [comment]
I don't think we can fix it now. Here is an open issue for it
https://github.com/pseudomuto/protoc-gen-doc/issues/406
