### ISSUE TITLE
NewValueTypeLeafListBytes crashes if precision array is too small

### ISSUE THREAD

**Issue by ray-milkey** [onosproject/onos-config#913]
**Describe the bug**
NewValueTypeLeafListBytes() throws an index out of bounds error if precision array is too small

**Comment by ray-milkey** [comment]
This test shows the bug:

func TestLeafListBytesCrash(t *testing.T) {
	bytes := []byte("12345678")
	typeOpts := []int32{4}
	value, err := NewTypedValue(bytes, ValueType_LEAFLIST_BYTES, typeOpts)
	assert.Assert(t, value == nil)
	assert.Assert(t, err != nil)
}

**Comment by SeanCondon** [comment]
I think typeOpts is meant to be the number of bytes. the sum of all type opts should be the same as the count of the bytes given - I can add this check to caseValueTypeLeafListBYTES()

**Comment by ray-milkey** [comment]
@SeanCondon I have a PR coming with a fix - please review when you can

**Comment by SeanCondon** [comment]
fixed by #914
