### ISSUE TITLE
Node ID is not properly set in Helm charts

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#958]
**Describe the bug**
Nodes use the `NODE_ID` environment as the unique ID for leader election. The Helm chart sets `NODE_NAME` but not `NODE_ID`. This results in multiple leaders with the same ID: `””`

**Expected behavior**
The cluster should elect only a single leader and a master per device. 

**Proposed solution**
Rename the `NODE_NAME` environment variable set in the Helm chart to `NODE_ID`.

**Comment by adibrastegarnia** [comment]
Fixed in onosproject/onos-helm-charts#181
