### ISSUE TITLE
Support configurable per-store partition groups

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#959]
ONOS Config currently expects to be given the name for a single partition group to be used for all stores. However, there are use cases that require using different protocols for different stores. In particular, leader election in single node clusters can be done using a simpler protocol that makes use of k8s features. onos-config should support per-store configurations for these use cases.

**Comment by adibrastegarnia** [comment]
@kuujo confirmed this is done. 
we can configure it via helm charts.
