### ISSUE TITLE
Add concurrency control for device states in multi-node clusters

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#960]
In multi-node clusters, device mastership changes can cause multiple nodes to believe themselves to be the master for a device at the same time, potentially resulting in erratic updates to device protocol states. And although onos-config may primarily be run in a single node configuration, multi-node clusters cannot be entirely avoided. Support for rolling updates will make this issue particularly relevant.

Config should use device attributes to implement concurrency control for device mastership. To do so, we simply need to include device mastership terms in device protocol state updates and relinquish mastership when a greater term is encountered.

**Comment by adibrastegarnia** [comment]
This issue is addressed for now until we migrate to use new topo API and perhaps use entity relationship to implement mastership .
