### ISSUE TITLE
Update device connectivity state on master only

### ISSUE THREAD

**Issue by kuujo** [onosproject/onos-config#962]
Any node can currently update connectivity info for a device. This means if a device disconnects from one node, connectivity is recorded as down for all nodes regardless of whether the master can still reach the device. Nodes should only attempt to become the master for a device once they’ve established a connection to it, and only the master should record the connectivity state for a device. This ensures mastership can only fail over to a node that can reach the device, and nodes that can’t reach the device cannot overwrite the connectivity state of nodes that can.

**Comment by adibrastegarnia** [comment]
This issue is also addressed.
