### ISSUE TITLE
Design certificate subsystem

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#97]
Certificate and secrets subsystem needs designing in order to accommodate NB, SB and internal certs

**Comment by tomikazi** [comment]
This should be something very lightweight, and preferably backed by the k8s cert tracking mechanism.

**Comment by Andrea-Campanella** [comment]
I think at the moment Stratum uses no certs so this can be lower priority

**Comment by Andrea-Campanella** [comment]
I did some reading on this, I think the best approach is to create a secret bases on the key and cert  with `kubectl`, load into into the pod as resources through the `secrets` api (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#secret-v1-core) then read them from `onos-config` through the k8s resource API fo the k8s cluster. The mapping device to certificate would be based on the `device.ID` e.g. `localhost-1-1.0.0`.

**Comment by Andrea-Campanella** [comment]
see https://drive.google.com/file/d/1HYFPvl_zGPS25PZT0HHdtopsmIQn3eJL/view?usp=sharing

**Comment by Andrea-Campanella** [comment]
done, design is approved, code will be created under `ones-test`
